# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.calc_genetic_sim <- function(prob_array) {
    .Call('qtl2scan_calc_genetic_sim', PACKAGE = 'qtl2scan', prob_array)
}

fit_linreg_eigenchol <- function(X, y) {
    .Call('qtl2scan_fit_linreg_eigenchol', PACKAGE = 'qtl2scan', X, y)
}

calc_rss_eigenchol <- function(X, y) {
    .Call('qtl2scan_calc_rss_eigenchol', PACKAGE = 'qtl2scan', X, y)
}

fit_linreg_eigenqr <- function(X, y) {
    .Call('qtl2scan_fit_linreg_eigenqr', PACKAGE = 'qtl2scan', X, y)
}

calc_rss_eigenqr <- function(X, y) {
    .Call('qtl2scan_calc_rss_eigenqr', PACKAGE = 'qtl2scan', X, y)
}

calc_mvrss_eigenchol <- function(X, Y) {
    .Call('qtl2scan_calc_mvrss_eigenchol', PACKAGE = 'qtl2scan', X, Y)
}

calc_mvrss_eigenqr <- function(X, Y) {
    .Call('qtl2scan_calc_mvrss_eigenqr', PACKAGE = 'qtl2scan', X, Y)
}

calc_rss_lapack <- function(X, Y, skip_dgels = FALSE, tol = 1e-10) {
    .Call('qtl2scan_calc_rss_lapack', PACKAGE = 'qtl2scan', X, Y, skip_dgels, tol)
}

cbind_imatrix <- function(mat1, mat2) {
    .Call('qtl2scan_cbind_imatrix', PACKAGE = 'qtl2scan', mat1, mat2)
}

cbind_3imatrix <- function(mat1, mat2, mat3) {
    .Call('qtl2scan_cbind_3imatrix', PACKAGE = 'qtl2scan', mat1, mat2, mat3)
}

cbind_nmatrix <- function(mat1, mat2) {
    .Call('qtl2scan_cbind_nmatrix', PACKAGE = 'qtl2scan', mat1, mat2)
}

cbind_3nmatrix <- function(mat1, mat2, mat3) {
    .Call('qtl2scan_cbind_3nmatrix', PACKAGE = 'qtl2scan', mat1, mat2, mat3)
}

rbind_imatrix <- function(mat1, mat2) {
    .Call('qtl2scan_rbind_imatrix', PACKAGE = 'qtl2scan', mat1, mat2)
}

rbind_3imatrix <- function(mat1, mat2, mat3) {
    .Call('qtl2scan_rbind_3imatrix', PACKAGE = 'qtl2scan', mat1, mat2, mat3)
}

rbind_nmatrix <- function(mat1, mat2) {
    .Call('qtl2scan_rbind_nmatrix', PACKAGE = 'qtl2scan', mat1, mat2)
}

rbind_3nmatrix <- function(mat1, mat2, mat3) {
    .Call('qtl2scan_rbind_3nmatrix', PACKAGE = 'qtl2scan', mat1, mat2, mat3)
}

