# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interpolate_map <- function(oldpos, oldmap, newmap) {
    .Call('qtl2scan_interpolate_map', PACKAGE = 'qtl2scan', oldpos, oldmap, newmap)
}

find_intervals <- function(pos, map, tol = 1e-8) {
    .Call('qtl2scan_find_intervals', PACKAGE = 'qtl2scan', pos, map, tol)
}

fit_linreg_eigenchol <- function(X, y) {
    .Call('qtl2scan_fit_linreg_eigenchol', PACKAGE = 'qtl2scan', X, y)
}

calc_coef_linreg_eigenchol <- function(X, y) {
    .Call('qtl2scan_calc_coef_linreg_eigenchol', PACKAGE = 'qtl2scan', X, y)
}

calc_coefSE_linreg_eigenchol <- function(X, y) {
    .Call('qtl2scan_calc_coefSE_linreg_eigenchol', PACKAGE = 'qtl2scan', X, y)
}

calc_rss_eigenchol <- function(X, y) {
    .Call('qtl2scan_calc_rss_eigenchol', PACKAGE = 'qtl2scan', X, y)
}

fit_linreg_eigenqr <- function(X, y, tol = 1e-12) {
    .Call('qtl2scan_fit_linreg_eigenqr', PACKAGE = 'qtl2scan', X, y, tol)
}

calc_coef_linreg_eigenqr <- function(X, y, tol = 1e-12) {
    .Call('qtl2scan_calc_coef_linreg_eigenqr', PACKAGE = 'qtl2scan', X, y, tol)
}

calc_coefSE_linreg_eigenqr <- function(X, y, tol = 1e-12) {
    .Call('qtl2scan_calc_coefSE_linreg_eigenqr', PACKAGE = 'qtl2scan', X, y, tol)
}

calc_rss_eigenqr <- function(X, y, tol = 1e-12) {
    .Call('qtl2scan_calc_rss_eigenqr', PACKAGE = 'qtl2scan', X, y, tol)
}

calc_mvrss_eigenchol <- function(X, Y) {
    .Call('qtl2scan_calc_mvrss_eigenchol', PACKAGE = 'qtl2scan', X, Y)
}

calc_mvrss_eigenqr <- function(X, Y, tol = 1e-12) {
    .Call('qtl2scan_calc_mvrss_eigenqr', PACKAGE = 'qtl2scan', X, Y, tol)
}

calc_resid_eigenchol <- function(X, Y) {
    .Call('qtl2scan_calc_resid_eigenchol', PACKAGE = 'qtl2scan', X, Y)
}

calc_resid_eigenqr <- function(X, Y, tol = 1e-12) {
    .Call('qtl2scan_calc_resid_eigenqr', PACKAGE = 'qtl2scan', X, Y, tol)
}

calc_rss_linreg <- function(X, Y, tol = 1e-12) {
    .Call('qtl2scan_calc_rss_linreg', PACKAGE = 'qtl2scan', X, Y, tol)
}

calc_coef_linreg <- function(X, y, tol = 1e-12) {
    .Call('qtl2scan_calc_coef_linreg', PACKAGE = 'qtl2scan', X, y, tol)
}

calc_coefSE_linreg <- function(X, y, tol = 1e-12) {
    .Call('qtl2scan_calc_coefSE_linreg', PACKAGE = 'qtl2scan', X, y, tol)
}

calc_resid_linreg <- function(X, Y, tol = 1e-12) {
    .Call('qtl2scan_calc_resid_linreg', PACKAGE = 'qtl2scan', X, Y, tol)
}

calc_resid_linreg_3d <- function(X, P, tol = 1e-12) {
    .Call('qtl2scan_calc_resid_linreg_3d', PACKAGE = 'qtl2scan', X, P, tol)
}

Rcpp_eigen_decomp <- function(A) {
    .Call('qtl2scan_Rcpp_eigen_decomp', PACKAGE = 'qtl2scan', A)
}

Rcpp_eigen_rotation <- function(K, y, X) {
    .Call('qtl2scan_Rcpp_eigen_rotation', PACKAGE = 'qtl2scan', K, y, X)
}

Rcpp_calc_logdetXpX <- function(X) {
    .Call('qtl2scan_Rcpp_calc_logdetXpX', PACKAGE = 'qtl2scan', X)
}

Rcpp_calcLL <- function(hsq, Kva, y, X, reml = TRUE, logdetXpX = NA_real_) {
    .Call('qtl2scan_Rcpp_calcLL', PACKAGE = 'qtl2scan', hsq, Kva, y, X, reml, logdetXpX)
}

Rcpp_fitLMM <- function(Kva, y, X, reml = TRUE, check_boundary = TRUE, logdetXpX = NA_real_, tol = 1e-4) {
    .Call('qtl2scan_Rcpp_fitLMM', PACKAGE = 'qtl2scan', Kva, y, X, reml, check_boundary, logdetXpX, tol)
}

Rcpp_fitLMM_mat <- function(Kva, Y, X, reml = TRUE, check_boundary = TRUE, logdetXpX = NA_real_, tol = 1e-4) {
    .Call('qtl2scan_Rcpp_fitLMM_mat', PACKAGE = 'qtl2scan', Kva, Y, X, reml, check_boundary, logdetXpX, tol)
}

find_matching_cols <- function(mat, tol = 1e-12) {
    .Call('qtl2scan_find_matching_cols', PACKAGE = 'qtl2scan', mat, tol)
}

find_lin_indep_cols <- function(mat, tol = 1e-12) {
    .Call('qtl2scan_find_lin_indep_cols', PACKAGE = 'qtl2scan', mat, tol)
}

formX_intcovar <- function(probs, addcovar, intcovar, position, has_intercept = TRUE) {
    .Call('qtl2scan_formX_intcovar', PACKAGE = 'qtl2scan', probs, addcovar, intcovar, position, has_intercept)
}

expand_genoprobs_intcovar <- function(probs, intcovar) {
    .Call('qtl2scan_expand_genoprobs_intcovar', PACKAGE = 'qtl2scan', probs, intcovar)
}

weighted_matrix <- function(mat, weights) {
    .Call('qtl2scan_weighted_matrix', PACKAGE = 'qtl2scan', mat, weights)
}

weighted_3darray <- function(array, weights) {
    .Call('qtl2scan_weighted_3darray', PACKAGE = 'qtl2scan', array, weights)
}

matrix_x_matrix <- function(X, Y) {
    .Call('qtl2scan_matrix_x_matrix', PACKAGE = 'qtl2scan', X, Y)
}

matrix_x_vector <- function(X, y) {
    .Call('qtl2scan_matrix_x_vector', PACKAGE = 'qtl2scan', X, y)
}

matrix_x_3darray <- function(X, A) {
    .Call('qtl2scan_matrix_x_3darray', PACKAGE = 'qtl2scan', X, A)
}

random_int <- function(n, low, high) {
    .Call('qtl2scan_random_int', PACKAGE = 'qtl2scan', n, low, high)
}

get_permutation <- function(n) {
    .Call('qtl2scan_get_permutation', PACKAGE = 'qtl2scan', n)
}

permute_nvector <- function(n_perm, x) {
    .Call('qtl2scan_permute_nvector', PACKAGE = 'qtl2scan', n_perm, x)
}

permute_ivector <- function(n_perm, x) {
    .Call('qtl2scan_permute_ivector', PACKAGE = 'qtl2scan', n_perm, x)
}

permute_nvector_stratified <- function(n_perm, x, strata, n_strata = -1L) {
    .Call('qtl2scan_permute_nvector_stratified', PACKAGE = 'qtl2scan', n_perm, x, strata, n_strata)
}

permute_ivector_stratified <- function(n_perm, x, strata, n_strata = -1L) {
    .Call('qtl2scan_permute_ivector_stratified', PACKAGE = 'qtl2scan', n_perm, x, strata, n_strata)
}

scan_hk_onechr_nocovar <- function(genoprobs, pheno, tol = 1e-12) {
    .Call('qtl2scan_scan_hk_onechr_nocovar', PACKAGE = 'qtl2scan', genoprobs, pheno, tol)
}

scan_hk_onechr <- function(genoprobs, pheno, addcovar, tol = 1e-12) {
    .Call('qtl2scan_scan_hk_onechr', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, tol)
}

scan_hk_onechr_weighted <- function(genoprobs, pheno, addcovar, weights, tol = 1e-12) {
    .Call('qtl2scan_scan_hk_onechr_weighted', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, weights, tol)
}

scan_hk_onechr_intcovar_highmem <- function(genoprobs, pheno, addcovar, intcovar, tol = 1e-12) {
    .Call('qtl2scan_scan_hk_onechr_intcovar_highmem', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, tol)
}

scan_hk_onechr_intcovar_weighted_highmem <- function(genoprobs, pheno, addcovar, intcovar, weights, tol = 1e-12) {
    .Call('qtl2scan_scan_hk_onechr_intcovar_weighted_highmem', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, weights, tol)
}

scan_hk_onechr_intcovar_lowmem <- function(genoprobs, pheno, addcovar, intcovar, tol = 1e-12) {
    .Call('qtl2scan_scan_hk_onechr_intcovar_lowmem', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, tol)
}

scan_hk_onechr_intcovar_weighted_lowmem <- function(genoprobs, pheno, addcovar, intcovar, weights, tol = 1e-12) {
    .Call('qtl2scan_scan_hk_onechr_intcovar_weighted_lowmem', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, weights, tol)
}

scan_lmm_onechr <- function(genoprobs, pheno, addcovar, eigenvec, weights, tol = 1e-12) {
    .Call('qtl2scan_scan_lmm_onechr', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, eigenvec, weights, tol)
}

scan_lmm_onechr_intcovar_highmem <- function(genoprobs, pheno, addcovar, intcovar, eigenvec, weights, tol = 1e-12) {
    .Call('qtl2scan_scan_lmm_onechr_intcovar_highmem', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, eigenvec, weights, tol)
}

scan_lmm_onechr_intcovar_lowmem <- function(genoprobs, pheno, addcovar, intcovar, eigenvec, weights, tol = 1e-12) {
    .Call('qtl2scan_scan_lmm_onechr_intcovar_lowmem', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, eigenvec, weights, tol)
}

scancoef_hk_addcovar <- function(genoprobs, pheno, addcovar, weights, tol = 1e-12) {
    .Call('qtl2scan_scancoef_hk_addcovar', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, weights, tol)
}

scancoef_hk_intcovar <- function(genoprobs, pheno, addcovar, intcovar, weights, tol = 1e-12) {
    .Call('qtl2scan_scancoef_hk_intcovar', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, weights, tol)
}

scancoefSE_hk_addcovar <- function(genoprobs, pheno, addcovar, weights, tol = 1e-12) {
    .Call('qtl2scan_scancoefSE_hk_addcovar', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, weights, tol)
}

scancoefSE_hk_intcovar <- function(genoprobs, pheno, addcovar, intcovar, weights, tol = 1e-12) {
    .Call('qtl2scan_scancoefSE_hk_intcovar', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, weights, tol)
}

scancoef_lmm_addcovar <- function(genoprobs, pheno, addcovar, eigenvec, weights, tol = 1e-12) {
    .Call('qtl2scan_scancoef_lmm_addcovar', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, eigenvec, weights, tol)
}

scancoef_lmm_intcovar <- function(genoprobs, pheno, addcovar, intcovar, eigenvec, weights, tol = 1e-12) {
    .Call('qtl2scan_scancoef_lmm_intcovar', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, eigenvec, weights, tol)
}

scancoefSE_lmm_addcovar <- function(genoprobs, pheno, addcovar, eigenvec, weights, tol = 1e-12) {
    .Call('qtl2scan_scancoefSE_lmm_addcovar', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, eigenvec, weights, tol)
}

scancoefSE_lmm_intcovar <- function(genoprobs, pheno, addcovar, intcovar, eigenvec, weights, tol = 1e-12) {
    .Call('qtl2scan_scancoefSE_lmm_intcovar', PACKAGE = 'qtl2scan', genoprobs, pheno, addcovar, intcovar, eigenvec, weights, tol)
}

